version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: *
    environment:
      POSTGRES_DB: *
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - *:/var/lib/postgresql/data
