version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: goth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data
