x-mysql: &mysql
  DB_STRING: "mysql://admin:admin@tcp(mysql:3306)/goth"

x-postgres: &postgres
  DB_STRING: "postgresql://admin:admin@postgres:5432/goth?sslmode=disable"

x-goth: &goth
  pid: "host" # Prefork enabled requires PID != 1
  environment:
  ports:
    - "3000:3000"

x-migrate: &migrate
  image: migrate/migrate:latest
  volumes:
    - ".:/data:ro"

services:
  # goth-mysql:
  #   <<: *goth
  #   build:
  #     context: .
  #     args:
  #       DB_ENGINE: "mysql"
  #   environment:
  #     <<: *mysql
  #   ports:
  #     - "3001:3000"
  #
  # mysql:
  #   image: mariadb:latest
  #   restart: unless-stopped
  #   environment:
  #     MARIADB_RANDOM_ROOT_PASSWORD: true
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin
  #     MYSQL_DATABASE: goth
  #   healthcheck:
  #     test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
  #     start_period: 10s
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./tmp/mariadb:/var/lib/mysql
  #
  # migrate-mysql:
  #   <<: *migrate
  #   entrypoint:
  #     - "/bin/sh"
  #     - "-c"
  #     - "migrate -database $$DB_STRING -path $$MIG_PATH -verbose up "
  #   environment:
  #     <<: *mysql
  #     MIG_PATH: "/data/database/mysql/migrations/"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  goth-postgres:
    <<: *goth
    build:
      context: .
      args:
        DB_ENGINE: "postgresql"
    environment:
      <<: *postgres
    ports:
      - "3002:3000"

  postgres:
    image: postgres:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: goth
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data

  migrate-postgres:
    <<: *migrate
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "migrate -database $$DB_STRING -path $$MIG_PATH -verbose up "
    environment:
      <<: *postgres
      MIG_PATH: "/data/database/postgresql/migrations/"
    depends_on:
      postgres:
        condition: service_healthy

  adminer:
    image: adminer:latest
    restart: unless-stopped
    volumes:
      - ".:/data"
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        cat <<-EOF >/var/www/html/plugins-enabled/login-with-empty-password.php
        <?php
        class AdminerLoginWithEmptyPassword {
          function login() {
            return true;
          }
        }

        return new AdminerLoginWithEmptyPassword();
        EOF

        /usr/local/bin/entrypoint.sh php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - "8800:8080"
