// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProduct(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	// products
	GetProduct(ctx context.Context, id int64) (Product, error)
	// users
	GetUser(ctx context.Context, id int64) (User, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
