//go:build postgresql || postgres

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	Title       string
	Description string
	Amount      string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	ID          int64
}

type User struct {
	Email     string
	Username  string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	ID        int64
}
