//go:build sqlite || sqlite3 || (!postgresql && !postgres && !mysql && !mariadb)

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repo

import (
	"context"
)

type Querier interface {
	ActiveSearchProduct(ctx context.Context, arg ActiveSearchProductParams) ([]ActiveSearchProductRow, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteProductByID(ctx context.Context, productID int64) error
	ListProducts(ctx context.Context) ([]Product, error)
	ReadProductByID(ctx context.Context, productID int64) (Product, error)
	ReadProductByTitle(ctx context.Context, productName string) ([]Product, error)
	UpdateProductByID(ctx context.Context, arg UpdateProductByIDParams) error
}

var _ Querier = (*Queries)(nil)
