//go:build postgresql

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Amount      string           `json:"amount"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	ID          int64            `json:"id"`
}

type User struct {
	Email     string           `json:"email"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	ID        int64            `json:"id"`
}
