//go:build postgresql

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: products.sql

package store

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  title, description, amount
) VALUES (
  $1, $2, $3
)
RETURNING title, description, amount, created_at, updated_at, id
`

type CreateProductParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Amount      string `json:"amount"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Title, arg.Description, arg.Amount)
	var i Product
	err := row.Scan(
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT title, description, amount, created_at, updated_at, id FROM products
WHERE id = $1 LIMIT 1
`

// products
func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
	)
	return i, err
}

const getProductByTitle = `-- name: GetProductByTitle :many
SELECT title, description, amount, created_at, updated_at, id FROM products
WHERE title LIKE $1
`

func (q *Queries) GetProductByTitle(ctx context.Context, title string) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductByTitle, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.Title,
			&i.Description,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT title, description, amount, created_at, updated_at, id FROM products
ORDER BY title
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.Title,
			&i.Description,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET 
title = $1,
description = $2,
amount = $3
WHERE id = $4
`

type UpdateProductParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Amount      string `json:"amount"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.Title,
		arg.Description,
		arg.Amount,
		arg.ID,
	)
	return err
}
